baseURL = "https://anil.battalahalli.me"
languageCode = "en-us"
title = "Chaos"
theme = [ "PaperMod" ]
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$"]


[markup.goldmark.renderer]
unsafe = true

[params.profileMode]
enabled = true
title = "Bhaskar Pandit (ಭಾಸ್ಕರ್ ಪಂಡಿತ್)"
subtitle = "My name is Bhaskar Pandit ([**ಭಾಸ್ಕರ್ ಪಂಡಿತ್**](https://en.wikipedia.org/wiki/Kannada)) and this is the stuff that I do to Deploy. [More about me **here**](/about/)."
imageUrl = "home/chaotic_swirls.gif"
imageWidth = 220
imageHeight = 220

[params.social]
email = "bhaskarpanditmn@gmail.com"
linkedin = "bhaskar-pandit-m-n-67401a29b"
github = "BhaskPand"

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 30

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 25

[[menu.main]]
name = "Projects"
# url = "/statistics/"
url = "/stats-projects/"
weight = 10

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5

# [[menu.main]]
# name = "Self Study"
# url = "/selfstudy/"
# weight = 12
